name: Terraform Apply (DB)

on:
  push:
    branches:
      - main  # Ou o branch que você usa para alterações na infra do banco

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production  # Ou o ambiente que você configurou
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend-config="key=terraform.tfstate"  # Ou configure outro backend

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan